### ISSUE TITLE
Can't modify Dock even when contents_immutable set to FALSE

### ISSUE THREAD

**Issue by jimratliff** [Error-freeIT/Dock-Master#1]
I created a Dock Master package, ran it, but the resulting Docks (i.e., the Dock on each account) cannot be modified. (I can't drag an item off, and Options shows only "Open at Login" and "Show in Finder" but not "Remove from Dock".

By default, the template option "contents_immutable" is set to FALSE, which I would expect would mean that I can modify the Dock.

I just now realized that the column "Applies to Package" has neither TRUE nor FALSE for this "contents_immutable" item. So I guess it's unclear whether this item is supposed to apply to packages.

**Comment by Error-freeIT** [comment]
Hello Jim,
You just need to add the removable key to each removable app. For example, a removable Safari would be:
`<dict>
<key>cfurl_string</key>
<string>/Applications/Safari.app</string>
<key>removable</key>
<true/>
</dict>`

**Comment by jimratliff** [comment]
Thanks for the super-fast response! That fixed my problem.
