### ISSUE TITLE
Dock not applying to mobile accounts

### ISSUE THREAD

**Issue by Fgeronimo** [Error-freeIT/Dock-Master#2]
I am attempting to push the package version of Dock-Master to mobile accounts and existing accounts. Existing accounts show the correct dock but when I first log into a mobile account, the dock comes up with just the finder and the trash icon. Below is my payload generated.

`<?xml version="1.0" encoding="UTF-8"?> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"> <plist version="1.0"> <dict> <key>autohide</key> <false/> <key>contents-immutable</key> <false/> <key>largesize</key> <integer>128</integer> <key>launchanim</key> <true/> <key>launchanim-immutable</key> <false/> <key>magnification</key> <false/> <key>magnify-immutable</key> <false/> <key>magsize-immutable</key> <false/> <key>mineffect</key> <string>genie</string> <key>mineffect-immutable</key> <false/> <key>minimize-to-application</key> <false/> <key>minimize-to-application-immutable</key> <false/> <key>orientation</key> <string>bottom</string> <key>position-immutable</key> <false/> <key>show-process-indicators</key> <true/> <key>show-process-indicators-immutable</key> <false/> <key>size-immutable</key> <false/> <key>static-apps</key> <array> <dict> <key>tile-data</key> <dict> <key>file-data</key> <dict> <key>_CFURLString</key> <string>/Applications/Launchpad.app</string> <key>_CFURLStringType</key> <integer>0</integer> </dict> </dict> <key>tile-type</key> <string>file-tile</string> </dict> <dict> <key>tile-data</key> <dict> <key>file-data</key> <dict> <key>_CFURLString</key> <string>/Applications/Google Chrome.app</string> <key>_CFURLStringType</key> <integer>0</integer> </dict> </dict> <key>tile-type</key> <string>file-tile</string> </dict> <dict> <key>tile-data</key> <dict> <key>file-data</key> <dict> <key>_CFURLString</key> <string>/Applications/Mail.app</string> <key>_CFURLStringType</key> <integer>0</integer> </dict> </dict> <key>tile-type</key> <string>file-tile</string> </dict> <dict> <key>tile-data</key> <dict> <key>file-data</key> <dict> <key>_CFURLString</key> <string>/Applications/Contacts.app</string> <key>_CFURLStringType</key> <integer>0</integer> </dict> </dict> <key>tile-type</key> <string>file-tile</string> </dict> <dict> <key>tile-data</key> <dict> <key>file-data</key> <dict> <key>_CFURLString</key> <string>/Applications/Calendar.app</string> <key>_CFURLStringType</key> <integer>0</integer> </dict> </dict> <key>tile-type</key> <string>file-tile</string> </dict> <dict> <key>tile-data</key> <dict> <key>file-data</key> <dict> <key>_CFURLString</key> <string>/Applications/Notes.app</string> <key>_CFURLStringType</key> <integer>0</integer> </dict> </dict> <key>tile-type</key> <string>file-tile</string> </dict> <dict> <key>tile-data</key> <dict> <key>file-data</key> <dict> <key>_CFURLString</key> <string>/Applications/Slack.app</string> <key>_CFURLStringType</key> <integer>0</integer> </dict> </dict> <key>tile-type</key> <string>file-tile</string> </dict> <dict> <key>tile-data</key> <dict> <key>file-data</key> <dict> <key>_CFURLString</key> <string>/Applications/Self Service.app</string> <key>_CFURLStringType</key> <integer>0</integer> </dict> </dict> <key>tile-type</key> <string>file-tile</string> </dict> <dict> <key>tile-data</key> <dict> <key>file-data</key> <dict> <key>_CFURLString</key> <string>/Applications/System Preferences.app</string> <key>_CFURLStringType</key> <integer>0</integer> </dict> </dict> <key>tile-type</key> <string>file-tile</string> </dict> </array> <key>static-others</key> <array> <dict> <key>tile-data</key> <dict> <key>arrangement</key> <integer>1</integer> <key>displayas</key> <integer>2</integer> <key>home directory relative</key> <string>~/Downloads</string> <key>label</key> <string>Downloads</string> <key>showas</key> <integer>4</integer> </dict> <key>tile-type</key> <string>directory-tile</string> </dict> </array> <key>tilesize</key> <integer>68</integer> <key>version</key> <integer>1</integer> </dict> </plist>`

**Comment by Error-freeIT** [comment]
Can you please tell me:
- the version of OS X you are deploying the package to
- how are the mobile accounts created (e.g. script, manually, AD, etc.)

**Comment by Fgeronimo** [comment]
OSX Version: 10.11.6
Accounts are created in AD

**Comment by Error-freeIT** [comment]
Today I was able to replicate the issue. The AD mobile accounts do in fact contain the expected com.apple.dock.plist (copied from User Template), yet the user's dock only displays Finder and Trash.

This behaviour is due to MCX settings coming from Active Directory. You will find the settings being applied to each AD user under: /Library/Managed Preferences/accountnamehere

You can manually disable MCX settings on a client for a specific user with the following command:
`sudo dscl . -delete /Users/accountnamehere dsAttrTypeStandard:MCXSettings`

**Comment by klou** [comment]
I compared the produced ```com.apple.dock.plist``` to a previous payload (from the web version), and this (CLI-version) has ```static-apps``` and ```static-others``` keys instead of ```persistent-apps``` and ```persistent-others```.

Once I reverted the change manually, it works.  (on 10.12.2)
