### ISSUE TITLE
others

### ISSUE THREAD

**Issue by cliftoja** [Error-freeIT/Dock-Master#8]
I can never get anything in the others array to work.  All I'm trying to do is add downloads.   It never shows up.  And the Jamf Config profile interface only allows me to add ~/Downloads, which doesn't work either, unlike Documents which is just a check box and it works then but not if I add it via the mobile config.

**Comment by Error-freeIT** [comment]
I have a feeling that Jamf Pro is removing/ignoring certain parts of the configuration profile when uploaded. Does the profile work as expected if you manually install it on a device, by simply double-clicking the .mobileconfig file?
If yes, you can:

- Raise a ticket with Jamf to fix the bug.
- Deploy a package (.pkg) that installs the configuration profile. [This might be useful](https://github.com/timsutton/make-profile-pkg).

**Comment by Error-freeIT** [comment]
Signing the profile before uploading it to Jamf is the current solution.
